## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [1]:
import pandas as pd
import numpy as np

In [5]:
np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(16, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [6]:
df_fis

    Qt_acertos
0            0
1            3
2            9
3            5
4            5
..         ...
95          11
96          10
97           3
98           7
99          11

[100 rows x 1 columns]

In [7]:
#Consolidando os DFs e exibindo a quantidade de acertos de cada disciplina

df_Acertos = pd.DataFrame({
    'Matemática':(df_mat['Qt_acertos']),
    'Português':(df_por['Qt_acertos']),
    'Geografia':(df_geo['Qt_acertos']),
    'Inglês':(df_ing['Qt_acertos']),
    'História':(df_his['Qt_acertos']),
    'Física':(df_fis['Qt_acertos']),
    'Química':(df_qui['Qt_acertos'])
})

df_Acertos

    Matemática  Português  Geografia  Inglês  História  Física  Química
0            6         14          3       5         5       0        1
1           14         13          5       3         4       3        2
2           10          2          6       4         5       9       11
3            7          0          1       4         4       5        0
4            6          4          2       7         5       5        0
..         ...        ...        ...     ...       ...     ...      ...
95           7          0          3       0         4      11        6
96           2         13          0       7         5      10        4
97           0          0          1       0         1       3        9
98           2          9          0       3         1       7        9
99           4          3          7       3         5      11        6

[100 rows x 7 columns]

In [8]:
# 1) (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.

df_percentuais = pd.DataFrame({
    'Matemática':(df_mat['Qt_acertos'] / 24)*100,
    'Português':(df_por['Qt_acertos'] / 18)*100,
    'Geografia':(df_geo['Qt_acertos'] / 8)*100,
    'Inglês':(df_ing['Qt_acertos'] / 8)*100,
    'História':(df_his['Qt_acertos'] / 8)*100,
    'Física':(df_fis['Qt_acertos'] / 12)*100,
    'Química':(df_qui['Qt_acertos'] / 12)*100
})
df_percentuais

    Matemática  Português  Geografia  Inglês  História     Física    Química
0    25.000000  77.777778       37.5    62.5      62.5   0.000000   8.333333
1    58.333333  72.222222       62.5    37.5      50.0  25.000000  16.666667
2    41.666667  11.111111       75.0    50.0      62.5  75.000000  91.666667
3    29.166667   0.000000       12.5    50.0      50.0  41.666667   0.000000
4    25.000000  22.222222       25.0    87.5      62.5  41.666667   0.000000
..         ...        ...        ...     ...       ...        ...        ...
95   29.166667   0.000000       37.5     0.0      50.0  91.666667  50.000000
96    8.333333  72.222222        0.0    87.5      62.5  83.333333  33.333333
97    0.000000   0.000000       12.5     0.0      12.5  25.000000  75.000000
98    8.333333  50.000000        0.0    37.5      12.5  58.333333  75.000000
99   16.666667  16.666667       87.5    37.5      62.5  91.666667  50.000000

[100 rows x 7 columns]

In [9]:
# 2) (operações entre *DataFrames) Calcule o total de acertos de cada aluno.
df_total = df_mat + df_por + df_geo + df_ing + df_his + df_fis + df_qui
df_total

    Qt_acertos
0           34
1           44
2           47
3           21
4           29
..         ...
95          31
96          41
97          14
98          31
99          39

[100 rows x 1 columns]

In [10]:
# 3) Calcule o porcentual geral de cada aluno.
df_percentual_geral = (df_total / 90)*100
df_percentual_geral

    Qt_acertos
0    37.777778
1    48.888889
2    52.222222
3    23.333333
4    32.222222
..         ...
95   34.444444
96   45.555556
97   15.555556
98   34.444444
99   43.333333

[100 rows x 1 columns]

In [11]:
# 4) Suponha que a nota de corte para a segunda fase seja 45. 
#Quantos alunos tiveram nota maior que 45?
total_gt_45 = df_total[df_total['Qt_acertos'] > 45]
total_gt_45.count()

Qt_acertos    19
dtype: int64

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [12]:
# Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. 
#Monte um novo DataFrame com os alunos desqualificados por este critério.

#dataframe com o total das as notas dos desqualificados

df_desqualificados_total = df_total[(df_mat['Qt_acertos'] == 0) | 
                      (df_fis['Qt_acertos'] == 0) | 
                      (df_qui['Qt_acertos'] == 0)]

df_desqualificados_total

    Qt_acertos
0           34
3           21
4           29
8           42
10          23
11          37
14          35
22          26
27          45
41          42
44          35
48          31
50          43
52          25
58          30
64          42
65          23
69          40
71          26
72          33
73          41
80          25
87          41
90          38
94          37
97          14

In [13]:
# Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. 
#Monte um novo DataFrame com os alunos desqualificados por este critério.

#dataframe com  as notas dos desqualificados com todas as disciplinas

df_desqualificados = df_Acertos[(df_mat['Qt_acertos'] == 0) | 
                      (df_fis['Qt_acertos'] == 0) | 
                      (df_qui['Qt_acertos'] == 0)]

df_desqualificados

    Matemática  Português  Geografia  Inglês  História  Física  Química
0            6         14          3       5         5       0        1
3            7          0          1       4         4       5        0
4            6          4          2       7         5       5        0
8            7         13          7       0         4       0       11
10           1         10          2       2         4       4        0
11          11          8          0       7         0      11        0
14           0          9          3       3         6       4       10
22          11          0          5       0         7       3        0
27           6         13          7       3         7       0        9
41          16          5          3       5         5       0        8
44           7          9          5       4         6       0        4
48           9          4          7       3         1       7        0
50          17         11          0       5         7       0        3
52           1         11          2       7         0       4        0
58           7         15          3       2         1       2        0
64          14         13          6       2         7       0        0
65          12          0          2       2         4       3        0
69           0         13          3       5         0       9       10
71           8          3          0       5         4       6        0
72           0         12          7       5         3       3        3
73          11          8          7       4         0       0       11
80           0         13          0       4         2       3        3
87           7         14          2       4         6       0        8
90           0         15          7       7         2       3        4
94          11          3          3       7         5       0        8
97           0          0          1       0         1       3        9

In [14]:
#2) Quantos são esses alunos?

#df_eliminados.shape --> Retorna a quantidade de linhas e coluna do dataframe
len(df_desqualificados.index) #--> Retorna a quantidade de linhas do dataframe
#df_desqualificados_total.count()

26

In [15]:
#3) Qual a média desses alunos em história e geografia?

# Exibe a média de todas as disciplinas dos desqualificados

df = pd.DataFrame(df_desqualificados)
media = df.mean()
media

Matemática    6.730769
Português     8.461538
Geografia     3.384615
Inglês        3.923077
História      3.692308
Física        2.884615
Química       3.923077
dtype: float64

In [16]:
#3) Qual a média desses alunos em história?

df_desqualificados['História'].mean()

3.6923076923076925

In [17]:
#3) Qual a média desses alunos em geografia?

df_desqualificados['Geografia'].mean()

3.3846153846153846

In [18]:
#4) Monte um DataFrame com os alunos que passaram para a segunda fase. 
#Repare que estes alunos não podem ter sido desqualificados.

df_aprovados_2f = df_Acertos[(df_mat['Qt_acertos'] != 0) & 
                      (df_fis['Qt_acertos'] != 0) & 
                      (df_qui['Qt_acertos'] != 0)]
df_aprovados_2f

    Matemática  Português  Geografia  Inglês  História  Física  Química
1           14         13          5       3         4       3        2
2           10          2          6       4         5       9       11
5           10          9          0       2         2      10        2
6           10          6          4       6         3      11       10
7            3         14          0       0         0       4        4
..         ...        ...        ...     ...       ...     ...      ...
93           2          8          0       2         6       1        6
95           7          0          3       0         4      11        6
96           2         13          0       7         5      10        4
98           2          9          0       3         1       7        9
99           4          3          7       3         5      11        6

[74 rows x 7 columns]

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [19]:
arquivo = 'https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/PNI/vacina/uf/2021-05-23/uf%3DAC/part-00000-63e5bee2-3684-4286-b709-7fe85483b04e.c000.csv'

In [20]:
df_acre = pd.read_csv('registros_vacinacao_ACRE.csv', sep=';')
df_acre

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem
0,b19cd280-474c-4c22-a35d-8c06bc04a4e0-i0b0,2e091c9a37d3f50d1d705fc80c6448c6fc69b44da9e936...,69,1951-12-28,F,3,PARDA,120050.0,10.0,SENA MADUREIRA,...,210052A,FUNDACAO BUTANTAN,Organization/61189445000156,2021-03-23,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-25T03:27:19.000Z,NaN
1,a1acc0b6-1cf6-4c4b-adcb-06b473a0faaf-i0b0,f4e17a9e5354cb45e223d85eda02fb2f76048c801675f5...,81,1939-11-22,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,210110,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-29,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-30T16:03:14.000Z,NaN
2,af279a98-ba1f-47ea-8214-314a98040b0d-i0b0,6734b26bccf826130ebffa66575977bbe71477b12bcf42...,69,1951-08-14,M,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,210135,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-16,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-16T15:54:39.000Z,NaN
3,4879308e-5050-46bb-b8e2-11fa5646a05c-i0b0,84a341fd350c1ba7117fccbb4d2df417bc0fac0fffac37...,51,1969-12-15,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,202010040,FUNDACAO BUTANTAN,Organization/61189445000156,2021-02-19,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-10T14:40:54.000Z,NaN
4,000e911b-e3a4-4114-a735-d1f2e6e3797f-i0b0,c59571e19f368d4b0cf08cd3bcabb32e5cd8baad5340f6...,65,1955-11-21,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,212VCD001ZVB,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-03-29,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-04-03T19:44:28.000Z,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169066,1d8f6ea9-d3f5-4882-9fe4-9d2f3ef88d77-i0b0,8048cb43bf62574837987f9351325ab06d3bc3884ee2f7...,25,1995-02-05,F,5,INDIGENA,120035.0,10.0,MARECHAL THAUMATURGO,...,202010028,FUNDACAO BUTANTAN,Organization/61189445000156,2021-01-26,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-02-03T19:13:58.000Z,NaN
169067,77ff98a4-79fb-47c9-aafa-8bf45708c4bc-i0b0,0548218b49585839b8f83c202bccac61f6a9c48cc1ea94...,68,1953-02-03,M,4,AMARELA,120040.0,10.0,RIO BRANCO,...,212VCD001ZVB,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-03-25,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-04-03T21:20:19.000Z,NaN
169068,1da067bc-9989-4fa4-8838-e1e40cdfeebf-i0b0,de5f1131ff4f954cfb28ebdcb964b6e25e83620ce9df49...,65,1955-06-05,M,2,PRETA,120017.0,10.0,CAPIXABA,...,210077,FUNDACAO BUTANTAN,Organization/61189445000156,2021-03-30,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-31T20:38:55.000Z,NaN
169069,eacc22e0-6f78-460f-a8e7-d85c6129951e-i0b0,fd1fb8d6e5de6eceeb7bb8246243d3c5cf85cdca01d849...,76,1944-06-15,F,1,BRANCA,120040.0,10.0,RIO BRANCO,...,4120Z025,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-02-26,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-02-27T23:41:11.000Z,NaN
169070,02795bd0-b1a7-49c1-83ca-90a9f9b4b794-i0b0,a22dbf631ad78dc6961100cbd6ec5f12ee80cd25148d84...,81,1939-08-08,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,4120Z025,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-02-27,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-03-15T14:27:07.000Z,NaN

In [21]:
df_acre.head(5)

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem
0,b19cd280-474c-4c22-a35d-8c06bc04a4e0-i0b0,2e091c9a37d3f50d1d705fc80c6448c6fc69b44da9e936...,69,1951-12-28,F,3,PARDA,120050.0,10.0,SENA MADUREIRA,...,210052A,FUNDACAO BUTANTAN,Organization/61189445000156,2021-03-23,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-25T03:27:19.000Z,NaN
1,a1acc0b6-1cf6-4c4b-adcb-06b473a0faaf-i0b0,f4e17a9e5354cb45e223d85eda02fb2f76048c801675f5...,81,1939-11-22,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,210110,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-29,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-30T16:03:14.000Z,NaN
2,af279a98-ba1f-47ea-8214-314a98040b0d-i0b0,6734b26bccf826130ebffa66575977bbe71477b12bcf42...,69,1951-08-14,M,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,210135,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-16,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-16T15:54:39.000Z,NaN
3,4879308e-5050-46bb-b8e2-11fa5646a05c-i0b0,84a341fd350c1ba7117fccbb4d2df417bc0fac0fffac37...,51,1969-12-15,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,202010040,FUNDACAO BUTANTAN,Organization/61189445000156,2021-02-19,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-10T14:40:54.000Z,NaN
4,000e911b-e3a4-4114-a735-d1f2e6e3797f-i0b0,c59571e19f368d4b0cf08cd3bcabb32e5cd8baad5340f6...,65,1955-11-21,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,212VCD001ZVB,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-03-29,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-04-03T19:44:28.000Z,NaN

In [22]:
df_acre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169071 entries, 0 to 169070
Data columns (total 34 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   document_id                               169071 non-null  object
 1   paciente_id                               169071 non-null  object
 2   paciente_idade                            169071 non-null  int64
 3   paciente_datanascimento                   169071 non-null  object
 4   paciente_enumsexobiologico                169071 non-null  object
 5   paciente_racacor_codigo                   169071 non-null  int64
 6   paciente_racacor_valor                    169071 non-null  object
 7   paciente_endereco_coibgemunicipio         167802 non-null  float64
 8   paciente_endereco_copais                  167804 non-null  float64
 9   paciente_endereco_nmmunicipio             167804 non-null  object
 10  paciente_endereco_nmpais                  167804 non-null  object
 11  paciente_endereco_uf                      167802 non-null  object
 12  paciente_endereco_cep                     140711 non-null  float64
 13  paciente_nacionalidade_enumnacionalidade  168904 non-null  object
 14  estabelecimento_valor                     169071 non-null  int64
 15  estabelecimento_razaosocial               169071 non-null  object
 16  estalecimento_nofantasia                  169071 non-null  object
 17  estabelecimento_municipio_codigo          169071 non-null  int64
 18  estabelecimento_municipio_nome            169071 non-null  object
 19  estabelecimento_uf                        169071 non-null  object
 20  vacina_grupoatendimento_codigo            169071 non-null  int64
 21  vacina_grupoatendimento_nome              167965 non-null  object
 22  vacina_categoria_codigo                   167965 non-null  float64
 23  vacina_categoria_nome                     167467 non-null  object
 24  vacina_lote                               169071 non-null  object
 25  vacina_fabricante_nome                    169071 non-null  object
 26  vacina_fabricante_referencia              167680 non-null  object
 27  vacina_dataaplicacao                      169071 non-null  object
 28  vacina_descricao_dose                     169071 non-null  object
 29  vacina_codigo                             169071 non-null  int64
 30  vacina_nome                               169071 non-null  object
 31  sistema_origem                            169071 non-null  object
 32  data_importacao_rnds                      169071 non-null  object
 33  id_sistema_origem                         0 non-null       float64
dtypes: float64(5), int64(6), object(23)
memory usage: 43.9+ MB

In [23]:
# 1) Quantas vacinas estão registradas nessa base?

df_acre['vacina_nome'].unique() #exibe o valor único

array(['Covid-19-Coronavac-Sinovac/Butantan',
       'Vacina Covid-19 - Covishield', 'Covid-19-AstraZeneca',
       'Vacina covid-19 - BNT162b2 - BioNTech/Fosun Pharma/Pfizer',
       'Vacina covid-19 - Ad26.COV2.S - Janssen-Cilag'], dtype=object)

In [24]:
df_acre['vacina_nome'].nunique() #exibe a quantidade do valor único

5

In [25]:
# 2) Quantos pacientes foram vacinados? (considere um paciente para cada valor único de paciente_id)

df_acre['paciente_id'].nunique()

120517

In [26]:
# 3) Quantos pacientes únicos tomaram a primeira dose? 
#OBS: Há um caractere especial neste campo. Receba os valores do campo com o método .unique().

df_acre['vacina_descricao_dose'].value_counts()

    1ª Dose    120939
    2ª Dose     48107
    Dose           25
Name: vacina_descricao_dose, dtype: int64

In [27]:
# 3.1) solução alternativa

#Criei a coluna 1a_dose e inseri 1 
#para os valores que correspondesse a '1ª dose' da coluna vacina_descricao_dose

df_acre['1a_dose'] = 0

In [28]:
# 3.1) solução alternativa

#Inseri 1 para os valores que correspondesse a '1ª dose' da coluna vacina_descricao_dose

df_acre.loc[df_acre['vacina_descricao_dose'] == '\xa0\xa0\xa0\xa01ª\xa0Dose', '1a_dose'] = 1

In [29]:
df_acre[['vacina_descricao_dose','1a_dose']]

       vacina_descricao_dose  1a_dose
0                    1ª Dose        1
1                    2ª Dose        0
2                    1ª Dose        1
3                    2ª Dose        0
4                    1ª Dose        1
...                      ...      ...
169066               1ª Dose        1
169067               1ª Dose        1
169068               1ª Dose        1
169069               1ª Dose        1
169070               1ª Dose        1

[169071 rows x 2 columns]

In [30]:
# 3.1) solução alternativa

#Somei os valores da coluna '1ª dose' e é igual ao valor dado no count da solução acima

df_acre['1a_dose'].sum()

120939

In [31]:
# 4) Quantos pacientes com menos de 18 anos foram vacinados?

df_menor = df_acre[df_acre["paciente_idade"]<18]
df_menor['paciente_id'].nunique()

47

In [32]:
# 4) solução alternativa

df_menor = df_acre[df_acre["paciente_idade"]<18]
df_menor['paciente_idade'].value_counts() 

# OBSERVE: que o paciente que tomou mais de uma vacina não é contado de novo
#OBSERVE: que 3 pacientes o valor é igual a 'zero'. Nesse caso, é um paciente com menos de 1 ano? 
# Ou é paciente que não informou a idade?

17    30
16    12
13     4
0      3
12     2
3      1
8      1
1      1
14     1
Name: paciente_idade, dtype: int64

In [33]:
# 4.1) continuação da solução alternativa acima

df_menor = df_acre[df_acre["paciente_idade"]<18]
df_menor['paciente_idade'].value_counts().sum() #TOTAL da quantidade acima

55

In [34]:
# 5) Quantos estabelecimentos aplicaram vacina no Acre?

df_acre['estabelecimento_razaosocial'].nunique()

42

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [35]:
# 1) crie uma cópia do DataFrame original, contendo somente os registros de vacinas realizadas 
# a menores de 18 anos.

df_menor18 = df_acre[df_acre["paciente_idade"]<18].copy()
df_menor18.head()

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem,1a_dose
1567,fdca313f-b348-422d-94d4-f2c66a87868c-i0b0,f5e6b8c44f7c4d13a87c582def5e8d460435b02f26af8c...,17,2003-07-18,F,4,AMARELA,120025.0,10.0,EPITACIOLANDIA,...,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-05-12,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-05-13T16:16:42.000Z,NaN,1
6250,b7431955-1faa-4c1e-9246-7c1e7b8bb3cb-i0b0,e1a45c07e3c393d5f0eccf4204a7ceab338f4f06696ecb...,16,2004-05-18,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,FUNDACAO BUTANTAN,Organization/61189445000156,2021-01-29,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-02-06T14:02:07.000Z,NaN,1
9569,fdb8d3b6-14d9-4bcc-9cfe-acd46b4a317a-i0b0,7cf3b238383a70eeb26841c01817737c9706d5b231e8c2...,17,2004-01-23,F,99,SEM INFORMACAO,120020.0,10.0,CRUZEIRO DO SUL,...,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-05-15,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-05-18T03:17:02.000Z,NaN,1
11338,647e2301-3ba4-463a-8d1e-2b6f38a4d99e-i0b0,53eb7fed5faa26ad17ce21ee378f28e25399ab7e90bc05...,17,2003-05-04,F,4,AMARELA,120030.0,10.0,FEIJO,...,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-02-09,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-02-09T22:08:13.000Z,NaN,1
15144,7f469e03-bece-49d0-bebc-33ad98e27f54-i0b0,dbaa6420d8a815158387668d0a59a19cf2bb63958e35d1...,16,2004-08-22,F,5,INDIGENA,120035.0,10.0,MARECHAL THAUMATURGO,...,FUNDACAO BUTANTAN,Organization/61189445000156,2021-01-28,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-02-09T19:26:03.000Z,NaN,1

In [36]:
df_menor18.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 55 entries, 1567 to 164449
Data columns (total 35 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   document_id                               55 non-null     object
 1   paciente_id                               55 non-null     object
 2   paciente_idade                            55 non-null     int64
 3   paciente_datanascimento                   55 non-null     object
 4   paciente_enumsexobiologico                55 non-null     object
 5   paciente_racacor_codigo                   55 non-null     int64
 6   paciente_racacor_valor                    55 non-null     object
 7   paciente_endereco_coibgemunicipio         52 non-null     float64
 8   paciente_endereco_copais                  52 non-null     float64
 9   paciente_endereco_nmmunicipio             52 non-null     object
 10  paciente_endereco_nmpais                  52 non-null     object
 11  paciente_endereco_uf                      52 non-null     object
 12  paciente_endereco_cep                     42 non-null     float64
 13  paciente_nacionalidade_enumnacionalidade  55 non-null     object
 14  estabelecimento_valor                     55 non-null     int64
 15  estabelecimento_razaosocial               55 non-null     object
 16  estalecimento_nofantasia                  55 non-null     object
 17  estabelecimento_municipio_codigo          55 non-null     int64
 18  estabelecimento_municipio_nome            55 non-null     object
 19  estabelecimento_uf                        55 non-null     object
 20  vacina_grupoatendimento_codigo            55 non-null     int64
 21  vacina_grupoatendimento_nome              54 non-null     object
 22  vacina_categoria_codigo                   54 non-null     float64
 23  vacina_categoria_nome                     54 non-null     object
 24  vacina_lote                               55 non-null     object
 25  vacina_fabricante_nome                    55 non-null     object
 26  vacina_fabricante_referencia              53 non-null     object
 27  vacina_dataaplicacao                      55 non-null     object
 28  vacina_descricao_dose                     55 non-null     object
 29  vacina_codigo                             55 non-null     int64
 30  vacina_nome                               55 non-null     object
 31  sistema_origem                            55 non-null     object
 32  data_importacao_rnds                      55 non-null     object
 33  id_sistema_origem                         0 non-null      float64
 34  1a_dose                                   55 non-null     int64
dtypes: float64(5), int64(7), object(23)
memory usage: 15.5+ KB

In [37]:
# 2) crie uma lista das colunas desse DataFrame com o atributo de DataFrame .columns()

lista_colunas = df_menor18.columns.unique()
lista_colunas

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_datanascimento', 'paciente_enumsexobiologico',
       'paciente_racacor_codigo', 'paciente_racacor_valor',
       'paciente_endereco_coibgemunicipio', 'paciente_endereco_copais',
       'paciente_endereco_nmmunicipio', 'paciente_endereco_nmpais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumnacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaosocial', 'estalecimento_nofantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoatendimento_codigo',
       'vacina_grupoatendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataaplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem', 'data_importacao_rnds', 'id_sistema_origem',
       '1a_dose'],
      dtype='object')

In [38]:
# 3) Nesse DataFrame faça uma contagem do campo vacina_categoria_nome.

df_menor18['vacina_categoria_nome'].value_counts()

Povos Indígenas                     33
Trabalhadores de Saúde               9
Povos e Comunidades Tradicionais     9
Comorbidades                         2
Faixa Etária                         1
Name: vacina_categoria_nome, dtype: int64

In [39]:
# 4) a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, 
# faça uma lista com esses valores.

lista_variaveis = ['estabelecimento_valor',
       'estabelecimento_razaosocial', 'estalecimento_nofantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf']

In [42]:
df_menor_lista = lista_variaveis
df_menor_lista

['estabelecimento_valor',
 'estabelecimento_razaosocial',
 'estalecimento_nofantasia',
 'estabelecimento_municipio_codigo',
 'estabelecimento_municipio_nome',
 'estabelecimento_uf']

In [43]:
# 5) usando o método .loc, selecione somente essas variáveis

df_menor_lista2 = df_menor18.loc[:,'estabelecimento_valor':'estabelecimento_uf']

In [44]:
df_menor_lista2

,estabelecimento_valor,estabelecimento_razaosocial,estalecimento_nofantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1567,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOAO ALVES DA SILVA,120025,EPITACIOLANDIA,AC
6250,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
9569,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
11338,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
15144,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
17153,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
18361,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE PORTO WALTER,120039,PORTO WALTER,AC
18608,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
20204,6917682,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
20759,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
21119,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
27860,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
29127,6612385,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,120060,TARAUACA,AC
31200,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
35654,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
38412,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
51872,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
57405,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,POLO INDIGENA DE MANOEL URBANO,120034,MANOEL URBANO,AC
61131,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
62742,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
66922,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
68290,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
69882,5336171,SECRETARIA DE ESTADO DE SAUDE DO ACRE,HOSPITAL REGIONAL DO JURUA,120020,CRUZEIRO DO SUL,AC
70881,6697151,MINISTERIO DA SAUDE,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS,120050,SENA MADUREIRA,AC
75368,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
78289,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
79146,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
81424,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
84331,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
88619,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
89601,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
94858,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
95916,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
101402,3323307,PREFEITURA MUNICIPAL DE PORTO ACRE,UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE,120080,PORTO ACRE,AC
104776,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
111242,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
116510,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
119906,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
122656,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
123769,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
124696,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE PORTO WALTER,120039,PORTO WALTER,AC
135392,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
136851,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
139074,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,POLO INDIGENA DE MANOEL URBANO,120034,MANOEL URBANO,AC
140895,7123043,PREFEITURA MUNICIPAL DE JORDAO,SAUDE DA FAMILIA RIBEIRINHA,120032,JORDAO,AC
142027,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
149043,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
149795,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
152218,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
153347,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
155238,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
161227,6612385,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,120060,TARAUACA,AC
163168,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
164046,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
164449,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC

In [46]:
# 5) Aplique o método .drop_duplicates e crie uma lista com uma linha para cada estabelecimento,
# com os dados do estabelecimento

df_menor_lista = df_menor_lista2.drop_duplicates()
df_menor_lista.shape #(18, 6)

(18, 6)

In [47]:
df_menor_lista.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18 entries, 1567 to 140895
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   estabelecimento_valor             18 non-null     int64
 1   estabelecimento_razaosocial       18 non-null     object
 2   estalecimento_nofantasia          18 non-null     object
 3   estabelecimento_municipio_codigo  18 non-null     int64
 4   estabelecimento_municipio_nome    18 non-null     object
 5   estabelecimento_uf                18 non-null     object
dtypes: int64(2), object(4)
memory usage: 1008.0+ bytes

In [49]:
# 5) ... e crie uma lista com uma linha para cada estabelecimento com os dados do estabelecimento
df_menor_lista.T

,1567,6250,9569,11338,15144,17153,18361,18608,20204,21119,29127,57405,61131,68290,69882,70881,101402,140895
estabelecimento_valor,2001314,6917291,6159087,2000040,7625855,6748759,6308740,2001748,6917682,6428940,6612385,9648968,6430201,6955525,5336171,6697151,3323307,7123043
estabelecimento_razaosocial,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,PREFEITURA MUNICIPAL DE RIO BRANCO,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,PREFEITURA MUNICIPAL DE FEIJO,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,PREFEITURA MUNICIPAL DE PORTO WALTER,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,PREFEITURA MUNICIPAL DE ASSIS BRASIL,PREFEITURA MUNICIPAL DE TARAUACA,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,SECRETARIA DE ESTADO DE SAUDE DO ACRE,MINISTERIO DA SAUDE,PREFEITURA MUNICIPAL DE PORTO ACRE,PREFEITURA MUNICIPAL DE JORDAO
estalecimento_nofantasia,ESF JOAO ALVES DA SILVA,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,CENTRO DE SAUDE DIAMANTINO MACEDO,POLO BASE DE MARECHAL THAUMATURGO,POLO BASE DE FEIJO,POLO BASE DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,POLO BASE DE CRUZEIRO DO SUL,POLO BASE DE ASSIS BRASIL,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,POLO INDIGENA DE MANOEL URBANO,POLO BASE INDIGENA,POLO BASE DE MANCIO LIMA,HOSPITAL REGIONAL DO JURUA,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS,UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE,SAUDE DA FAMILIA RIBEIRINHA
estabelecimento_municipio_codigo,120025,120040,120020,120030,120035,120030,120039,120039,120020,120005,120060,120034,120032,120033,120020,120050,120080,120032
estabelecimento_municipio_nome,EPITACIOLANDIA,RIO BRANCO,CRUZEIRO DO SUL,FEIJO,MARECHAL THAUMATURGO,FEIJO,PORTO WALTER,PORTO WALTER,CRUZEIRO DO SUL,ASSIS BRASIL,TARAUACA,MANOEL URBANO,JORDAO,MANCIO LIMA,CRUZEIRO DO SUL,SENA MADUREIRA,PORTO ACRE,JORDAO
estabelecimento_uf,AC,AC,AC,AC,AC,AC,AC,AC,AC,AC,AC,AC,AC,AC,AC,AC,AC,AC